# WebSSH one-command installer for Windows.
#
# Mirrors install.sh: it prepares a deployment directory with a generated
# application secret, an .env file, and a docker-compose.yml, then starts the
# published image through Docker Desktop.
#
# The script is idempotent: re-running it keeps the existing deployment
# directory, generated application secret, and TLS settings.
#
# Usage:
#   .\install.ps1 [-Mode docker] [-Dir .\webssh-deployment] [-Port 5000]
#   .\install.ps1 -Tls self-signed -Domain webssh.lan -Port 8443

[CmdletBinding()]
param(
    [ValidateSet('docker')]
    [string]$Mode = 'docker',

    [string]$Dir = '.\webssh-deployment',

    [ValidateRange(1, 65535)]
    [int]$Port = 5000,

    [ValidateSet('off', 'self-signed', 'manual', 'acme')]
    [string]$Tls = 'off',

    [string]$Domain = '',

    [string]$Email = '',

    [switch]$AllowInternalSsh,

    [switch]$NoStart,

    [switch]$NoPull
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$Image = 'ghcr.io/zhengwuji/web-ssh:latest'
$ReadyTimeoutSeconds = 120

function Write-Step {
    param([string]$Message)
    Write-Host $Message
}

function Write-WarningLine {
    param([string]$Message)
    Write-Warning $Message
}

function Stop-Install {
    param([string]$Message)
    Write-Error "ERROR: $Message"
    exit 1
}

if ($Tls -in @('self-signed', 'acme') -and [string]::IsNullOrWhiteSpace($Domain)) {
    Stop-Install "-Domain is required for -Tls $Tls."
}
if ($Tls -eq 'acme' -and [string]::IsNullOrWhiteSpace($Email)) {
    Stop-Install '-Email is required for -Tls acme.'
}

if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
    Stop-Install 'Docker Desktop is required. Install it from https://docs.docker.com/desktop/.'
}
docker compose version *> $null
if ($LASTEXITCODE -ne 0) {
    Stop-Install 'Docker Compose v2 is required (docker compose version failed).'
}

$InstallDir = New-Item -ItemType Directory -Force -Path $Dir | Select-Object -ExpandProperty FullName
$EnvFile = Join-Path $InstallDir '.env'
$ComposeFile = Join-Path $InstallDir 'docker-compose.yml'

function New-Secret {
    $bytes = New-Object 'byte[]' 32
    [System.Security.Cryptography.RandomNumberGenerator]::Fill($bytes)
    return -join ($bytes | ForEach-Object { $_.ToString('x2') })
}

function Get-ExistingSecret {
    param([string]$Path)

    if (-not (Test-Path $Path)) { return $null }
    foreach ($line in Get-Content -LiteralPath $Path) {
        if ($line -match '^SECRET_KEY=(.+)$') {
            $value = $Matches[1]
            if ($value -in @('changeme', 'secret', 'your-secret-key', '<your-secret-key>')) {
                return $null
            }
            return $value
        }
    }
    return $null
}

function Get-BlockInternalSsh {
    if ($AllowInternalSsh) { return 'false' }
    return 'true'
}

function Get-SecureCookies {
    if ($Tls -eq 'off') { return 'false' }
    return 'true'
}

function Get-Origins {
    if ($Tls -eq 'off') {
        return "http://localhost:$Port,http://127.0.0.1:$Port"
    }
    # Engine.IO validates the Origin header against CORS_ORIGINS, so the real
    # TLS hostname has to be listed or every browser connection is rejected.
    $Origins = "https://localhost:$Port,https://127.0.0.1:$Port"
    if (-not [string]::IsNullOrWhiteSpace($Domain)) {
        $Origins += ",https://${Domain}:$Port"
        if ($Port -eq 443) {
            $Origins += ",https://$Domain"
        }
    }
    return $Origins
}

$Secret = Get-ExistingSecret -Path $EnvFile
if ([string]::IsNullOrWhiteSpace($Secret)) {
    $Secret = New-Secret
}

$Stamp = (Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ')
$EnvLines = @(
    "# Generated by install.ps1 on $Stamp",
    "SECRET_KEY=$Secret",
    'DEPLOYMENT_PROFILE=homelab',
    "CORS_ORIGINS=$(Get-Origins)",
    'ALLOW_CORS_WILDCARD=false',
    "BLOCK_INTERNAL_SSH=$(Get-BlockInternalSsh)",
    "WEBSSH_TLS_MODE=$Tls"
)
if (-not [string]::IsNullOrWhiteSpace($Domain)) {
    $EnvLines += "WEBSSH_TLS_DOMAIN=$Domain"
}
if (-not [string]::IsNullOrWhiteSpace($Email)) {
    $EnvLines += "WEBSSH_TLS_EMAIL=$Email"
}
Set-Content -LiteralPath $EnvFile -Value $EnvLines -Encoding utf8NoBOM

$ComposeLines = @(
    "# Generated by install.ps1 on $Stamp",
    '# Edit .env, then run: docker compose up -d',
    '',
    'services:',
    '  webssh:',
    "    image: $Image",
    '    container_name: webssh',
    '    restart: unless-stopped',
    '    stop_grace_period: 40s',
    '    env_file:',
    '      - .env',
    '    environment:',
    '      - PORT=5000',
    '      - TRUSTED_PROXIES=0',
    "      - SESSION_COOKIE_SECURE=$(Get-SecureCookies)",
    '      - TMUX_ENABLED=true',
    '      - TMUX_DEFAULT=true',
    '      - TMUX_SESSION_PREFIX=webssh',
    '      - BACKUP_TEMP_DIR=/app/recovery',
    '      - BACKUP_RECOVERY_DURABLE=true',
    '    ports:',
    "      - `"$Port`:5000`""
)
if ($Tls -eq 'acme' -and $Port -ne 80) {
    # The ACME standalone challenge needs host port 80. Skip it when the chosen
    # application port already binds 80, which would be a duplicate mapping.
    $ComposeLines += '      - "80:80"'
}
$ComposeLines += @(
    '    volumes:',
    '      - webssh_data:/app/data',
    '      - webssh_recovery:/app/recovery',
    '    healthcheck:',
    '      test: ["CMD", "python", "healthcheck.py"]',
    '      interval: 30s',
    '      timeout: 5s',
    '      retries: 3',
    '      start_period: 10s',
    '',
    'volumes:',
    '  webssh_data:',
    '  webssh_recovery:',
    '    driver: local'
)
Set-Content -LiteralPath $ComposeFile -Value $ComposeLines -Encoding utf8NoBOM

if ($NoStart) {
    Write-Step "Prepared $InstallDir (not started)."
    Write-Step "Start it later with: cd `"$InstallDir`"; docker compose up -d"
    exit 0
}

if (-not $NoPull) {
    Write-Step 'Pulling the WebSSH image...'
    Push-Location $InstallDir
    try {
        docker compose pull --quiet
        if ($LASTEXITCODE -ne 0) {
            Write-WarningLine 'Image pull failed; continuing with any cached image.'
        }
    } finally {
        Pop-Location
    }
}

Write-Step 'Starting WebSSH...'
Push-Location $InstallDir
try {
    docker compose up -d
    if ($LASTEXITCODE -ne 0) {
        Stop-Install 'docker compose up failed.'
    }
} finally {
    Pop-Location
}

$Scheme = 'http'
if ($Tls -ne 'off') { $Scheme = 'https' }
$ReadyUrl = "$Scheme`://localhost:$Port/ready"

Write-Step "Waiting for $ReadyUrl ..."
$Deadline = (Get-Date).AddSeconds($ReadyTimeoutSeconds)
$Ready = $false
while ((Get-Date) -lt $Deadline) {
    try {
        Invoke-WebRequest -Uri $ReadyUrl -TimeoutSec 3 -UseBasicParsing *> $null
        $Ready = $true
        break
    } catch {
        Start-Sleep -Seconds 2
    }
}

if ($Ready) {
    Write-Step "WebSSH is ready at $Scheme`://localhost:$Port"
} else {
    Write-WarningLine "The readiness endpoint did not answer within ${ReadyTimeoutSeconds}s."
    Write-WarningLine 'Inspect the container logs before exposing this instance.'
}

Write-Step "Install directory: $InstallDir"
Write-Step "Follow logs with: cd `"$InstallDir`"; docker compose logs -f"
Write-Step 'Done.'
